-- Staffly Applications table schema
-- Run this SQL in your Supabase SQL Editor to create/update the Applications table.

CREATE TABLE IF NOT EXISTS "Applications" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL REFERENCES "Events"(id) ON DELETE CASCADE,
    volunteer_id bigint REFERENCES "Volunteers"(id) ON DELETE SET NULL,
    user_id uuid,
    email text,
    status text DEFAULT 'pending',
    applied_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE "Applications" ENABLE ROW LEVEL SECURITY;

-- Allow public read access ( Heads need to review applications )
CREATE POLICY IF NOT EXISTS "Allow public read access on Applications"
    ON "Applications"
    FOR SELECT
    TO anon, authenticated
    USING (true);

-- Allow authenticated volunteers to apply
CREATE POLICY IF NOT EXISTS "Allow authenticated insert on Applications"
    ON "Applications"
    FOR INSERT
    TO authenticated
    WITH CHECK (true);

-- Optional trigger to auto-update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_applications_updated_at ON "Applications";
CREATE TRIGGER update_applications_updated_at
    BEFORE UPDATE ON "Applications"
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
