-- Staffly Events table schema
-- Run this SQL in your Supabase SQL Editor to create/update the Events table.

-- Create the Events table if it does not exist
CREATE TABLE IF NOT EXISTS "Events" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text DEFAULT '',
    location text NOT NULL,
    event_date date NOT NULL,
    start_time time without time zone,
    end_time time without time zone,
    salary numeric DEFAULT 0,
    volunteer_limit integer DEFAULT 0,
    waitlist_limit integer DEFAULT 0,
    accepted_count integer DEFAULT 0,
    waitlist_count integer DEFAULT 0,
    status text DEFAULT 'upcoming',
    image_url text DEFAULT 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=800&q=80&auto=format&fit=crop',
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Enable Row Level Security (recommended)
ALTER TABLE "Events" ENABLE ROW LEVEL SECURITY;

-- Allow anonymous/public read access to events
CREATE POLICY IF NOT EXISTS "Allow public read access on Events"
    ON "Events"
    FOR SELECT
    TO anon, authenticated
    USING (true);

-- Allow authenticated users to create events (adjust as needed for organisers/heads)
CREATE POLICY IF NOT EXISTS "Allow authenticated insert on Events"
    ON "Events"
    FOR INSERT
    TO authenticated
    WITH CHECK (true);

-- Allow authenticated users to update events (optional)
CREATE POLICY IF NOT EXISTS "Allow authenticated update on Events"
    ON "Events"
    FOR UPDATE
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Optional trigger to auto-update the updated_at column
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_events_updated_at ON "Events";
CREATE TRIGGER update_events_updated_at
    BEFORE UPDATE ON "Events"
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
